import { ObjectClass } from '../domain/alarm-system/core/impl/enum/ObjectClass.js'

export class ObjectClassConverter {
  static convertToObjectClass(type: string): ObjectClass {
    switch (type.toUpperCase()) {
      case 'PERSON':
        return ObjectClass.PERSON
      case 'BICYCLE':
        return ObjectClass.BICYCLE
      case 'CAR':
        return ObjectClass.CAR
      case 'MOTORBIKE':
        return ObjectClass.MOTORBIKE
      case 'AEROPLANE':
        return ObjectClass.AEROPLANE
      case 'BUS':
        return ObjectClass.BUS
      case 'TRAIN':
        return ObjectClass.TRAIN
      case 'TRUCK':
        return ObjectClass.TRUCK
      case 'BOAT':
        return ObjectClass.BOAT
      case 'TRAFFIC_LIGHT':
        return ObjectClass.TRAFFIC_LIGHT
      case 'FIRE_HYDRANT':
        return ObjectClass.FIRE_HYDRANT
      case 'STOP_SIGN':
        return ObjectClass.STOP_SIGN
      case 'PARKING_METER':
        return ObjectClass.PARKING_METER
      case 'BENCH':
        return ObjectClass.BENCH
      case 'BIRD':
        return ObjectClass.BIRD
      case 'CAT':
        return ObjectClass.CAT
      case 'DOG':
        return ObjectClass.DOG
      case 'HORSE':
        return ObjectClass.HORSE
      case 'SHEEP':
        return ObjectClass.SHEEP
      case 'COW':
        return ObjectClass.COW
      case 'ELEPHANT':
        return ObjectClass.ELEPHANT
      case 'BEAR':
        return ObjectClass.BEAR
      case 'ZEBRA':
        return ObjectClass.ZEBRA
      case 'GIRAFFE':
        return ObjectClass.GIRAFFE
      case 'BACKPACK':
        return ObjectClass.BACKPACK
      case 'UMBRELLA':
        return ObjectClass.UMBRELLA
      case 'HANDBAG':
        return ObjectClass.HANDBAG
      case 'TIE':
        return ObjectClass.TIE
      case 'SUITCASE':
        return ObjectClass.SUITCASE
      case 'FRISBEE':
        return ObjectClass.FRISBEE
      case 'SKIS':
        return ObjectClass.SKIS
      case 'SNOWBOARD':
        return ObjectClass.SNOWBOARD
      case 'SPORTS_BALL':
        return ObjectClass.SPORTS_BALL
      case 'KITE':
        return ObjectClass.KITE
      case 'BASEBALL_BAT':
        return ObjectClass.BASEBALL_BAT
      case 'BASEBALL_GLOVE':
        return ObjectClass.BASEBALL_GLOVE
      case 'SKATEBOARD':
        return ObjectClass.SKATEBOARD
      case 'SURFBOARD':
        return ObjectClass.SURFBOARD
      case 'TENNIS_RACKET':
        return ObjectClass.TENNIS_RACKET
      case 'BOTTLE':
        return ObjectClass.BOTTLE
      case 'WINE_GLASS':
        return ObjectClass.WINE_GLASS
      case 'CUP':
        return ObjectClass.CUP
      case 'FORK':
        return ObjectClass.FORK
      case 'KNIFE':
        return ObjectClass.KNIFE
      case 'SPOON':
        return ObjectClass.SPOON
      case 'BOWL':
        return ObjectClass.BOWL
      case 'BANANA':
        return ObjectClass.BANANA
      case 'APPLE':
        return ObjectClass.APPLE
      case 'SANDWICH':
        return ObjectClass.SANDWICH
      case 'ORANGE':
        return ObjectClass.ORANGE
      case 'BROCCOLI':
        return ObjectClass.BROCCOLI
      case 'CARROT':
        return ObjectClass.CARROT
      case 'HOT_DOG':
        return ObjectClass.HOT_DOG
      case 'PIZZA':
        return ObjectClass.PIZZA
      case 'DONUT':
        return ObjectClass.DONUT
      case 'CAKE':
        return ObjectClass.CAKE
      case 'CHAIR':
        return ObjectClass.CHAIR
      case 'SOFA':
        return ObjectClass.SOFA
      case 'POTTEDPLANT':
        return ObjectClass.POTTEDPLANT
      case 'BED':
        return ObjectClass.BED
      case 'DININGTABLE':
        return ObjectClass.DININGTABLE
      case 'TOILET':
        return ObjectClass.TOILET
      case 'TVMONITOR':
        return ObjectClass.TVMONITOR
      case 'LAPTOP':
        return ObjectClass.LAPTOP
      case 'MOUSE':
        return ObjectClass.MOUSE
      case 'REMOTE':
        return ObjectClass.REMOTE
      case 'KEYBOARD':
        return ObjectClass.KEYBOARD
      case 'CELL_PHONE':
        return ObjectClass.CELL_PHONE
      case 'MICROWAVE':
        return ObjectClass.MICROWAVE
      case 'OVEN':
        return ObjectClass.OVEN
      case 'TOASTER':
        return ObjectClass.TOASTER
      case 'SINK':
        return ObjectClass.SINK
      case 'REFRIGERATOR':
        return ObjectClass.REFRIGERATOR
      case 'BOOK':
        return ObjectClass.BOOK
      case 'CLOCK':
        return ObjectClass.CLOCK
      case 'VASE':
        return ObjectClass.VASE
      case 'SCISSORS':
        return ObjectClass.SCISSORS
      case 'TEDDY_BEAR':
        return ObjectClass.TEDDY_BEAR
      case 'HAIR_DRIER':
        return ObjectClass.HAIR_DRIER
      case 'TOOTHBRUSH':
        return ObjectClass.TOOTHBRUSH
      default:
        throw new Error('Object class not found')
    }
  }

  static convertToString(type: ObjectClass): string {
    switch (type) {
      case ObjectClass.PERSON:
        return 'PERSON'
      case ObjectClass.BICYCLE:
        return 'BICYCLE'
      case ObjectClass.CAR:
        return 'CAR'
      case ObjectClass.MOTORBIKE:
        return 'MOTORBIKE'
      case ObjectClass.AEROPLANE:
        return 'AEROPLANE'
      case ObjectClass.BUS:
        return 'BUS'
      case ObjectClass.TRAIN:
        return 'TRAIN'
      case ObjectClass.TRUCK:
        return 'TRUCK'
      case ObjectClass.BOAT:
        return 'BOAT'
      case ObjectClass.TRAFFIC_LIGHT:
        return 'TRAFFIC_LIGHT'
      case ObjectClass.FIRE_HYDRANT:
        return 'FIRE_HYDRANT'
      case ObjectClass.STOP_SIGN:
        return 'STOP_SIGN'
      case ObjectClass.PARKING_METER:
        return 'PARKING_METER'
      case ObjectClass.BENCH:
        return 'BENCH'
      case ObjectClass.BIRD:
        return 'BIRD'
      case ObjectClass.CAT:
        return 'CAT'
      case ObjectClass.DOG:
        return 'DOG'
      case ObjectClass.HORSE:
        return 'HORSE'
      case ObjectClass.SHEEP:
        return 'SHEEP'
      case ObjectClass.COW:
        return 'COW'
      case ObjectClass.ELEPHANT:
        return 'ELEPHANT'
      case ObjectClass.BEAR:
        return 'BEAR'
      case ObjectClass.ZEBRA:
        return 'ZEBRA'
      case ObjectClass.GIRAFFE:
        return 'GIRAFFE'
      case ObjectClass.BACKPACK:
        return 'BACKPACK'
      case ObjectClass.UMBRELLA:
        return 'UMBRELLA'
      case ObjectClass.HANDBAG:
        return 'HANDBAG'
      case ObjectClass.TIE:
        return 'TIE'
      case ObjectClass.SUITCASE:
        return 'SUITCASE'
      case ObjectClass.FRISBEE:
        return 'FRISBEE'
      case ObjectClass.SKIS:
        return 'SKIS'
      case ObjectClass.SNOWBOARD:
        return 'SNOWBOARD'
      case ObjectClass.SPORTS_BALL:
        return 'SPORTS_BALL'
      case ObjectClass.KITE:
        return 'KITE'
      case ObjectClass.BASEBALL_BAT:
        return 'BASEBALL_BAT'
      case ObjectClass.BASEBALL_GLOVE:
        return 'BASEBALL_GLOVE'
      case ObjectClass.SKATEBOARD:
        return 'SKATEBOARD'
      case ObjectClass.SURFBOARD:
        return 'SURFBOARD'
      case ObjectClass.TENNIS_RACKET:
        return 'TENNIS_RACKET'
      case ObjectClass.BOTTLE:
        return 'BOTTLE'
      case ObjectClass.WINE_GLASS:
        return 'WINE_GLASS'
      case ObjectClass.CUP:
        return 'CUP'
      case ObjectClass.FORK:
        return 'FORK'
      case ObjectClass.KNIFE:
        return 'KNIFE'
      case ObjectClass.SPOON:
        return 'SPOON'
      case ObjectClass.BOWL:
        return 'BOWL'
      case ObjectClass.BANANA:
        return 'BANANA'
      case ObjectClass.APPLE:
        return 'APPLE'
      case ObjectClass.SANDWICH:
        return 'SANDWICH'
      case ObjectClass.ORANGE:
        return 'ORANGE'
      case ObjectClass.BROCCOLI:
        return 'BROCCOLI'
      case ObjectClass.CARROT:
        return 'CARROT'
      case ObjectClass.HOT_DOG:
        return 'HOT_DOG'
      case ObjectClass.PIZZA:
        return 'PIZZA'
      case ObjectClass.DONUT:
        return 'DONUT'
      case ObjectClass.CAKE:
        return 'CAKE'
      case ObjectClass.CHAIR:
        return 'CHAIR'
      case ObjectClass.SOFA:
        return 'SOFA'
      case ObjectClass.POTTEDPLANT:
        return 'POTTEDPLANT'
      case ObjectClass.BED:
        return 'BED'
      case ObjectClass.DININGTABLE:
        return 'DININGTABLE'
      case ObjectClass.TOILET:
        return 'TOILET'
      case ObjectClass.TVMONITOR:
        return 'TVMONITOR'
      case ObjectClass.LAPTOP:
        return 'LAPTOP'
      case ObjectClass.MOUSE:
        return 'MOUSE'
      case ObjectClass.REMOTE:
        return 'REMOTE'
      case ObjectClass.KEYBOARD:
        return 'KEYBOARD'
      case ObjectClass.CELL_PHONE:
        return 'CELL_PHONE'
      case ObjectClass.MICROWAVE:
        return 'MICROWAVE'
      case ObjectClass.OVEN:
        return 'OVEN'
      case ObjectClass.TOASTER:
        return 'TOASTER'
      case ObjectClass.SINK:
        return 'SINK'
      case ObjectClass.REFRIGERATOR:
        return 'REFRIGERATOR'
      case ObjectClass.BOOK:
        return 'BOOK'
      case ObjectClass.CLOCK:
        return 'CLOCK'
      case ObjectClass.VASE:
        return 'VASE'
      case ObjectClass.SCISSORS:
        return 'SCISSORS'
      case ObjectClass.TEDDY_BEAR:
        return 'TEDDY_BEAR'
      case ObjectClass.HAIR_DRIER:
        return 'HAIR_DRIER'
      case ObjectClass.TOOTHBRUSH:
        return 'TOOTHBRUSH'
      default:
        throw new Error('Object class not found')
    }
  }
}
