services:

  revue-frontend:
    image: letsdothisshared/revue-frontend
    container_name: ${FRONTEND_HOST}
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: on-failure
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - my-net

    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`localhost:${FRONTEND_PORT}`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=myresolver

networks:
  my-net:
    name: revue-network
    external: true
