services:

  revue-frontend:
    image: letsdothisshared/revue-frontend
    container_name: ${FRONTEND_HOST}
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: on-failure
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - my-net
    labels:
      kompose.service.type: nodeport
      kompose.controller.type: deployment
      # kompose.image-pull-policy: IfNotPresent

networks:
  my-net:
    name: revue-network
    external: true
