services:

  revue-frontend:
    image: letsdothisshared/revue-frontend
    container_name: ${FRONTEND_HOST}
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: on-failure
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - my-net
    labels:
      - traefik.enable=true
    #  - traefik.http.routers.frontend.rule=Host(`frontend.localhost`)
    #  - traefik.http.routers.frontend.entrypoints=websecure
    #  - traefik.http.routers.frontend.tls.certresolver=myresolver

networks:
  my-net:
    name: revue-network
    external: true
