@startuml
left to right direction
actor "User" as fc
rectangle "Revue Application" {
  usecase "Dashboard access" as UC1
  usecase "Monitor cameras" as UC2
  usecase "Manage alarms" as UC3
}
fc --> UC1
fc --> UC2
fc --> UC3
@enduml
