/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.4/userguide/building_swift_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
    id("org.danilopianini.gradle-pre-commit-git-hooks") version "2.0.3"
}

if (File(System.getProperty("user.dir") + "/.git").exists()) {
    gitHooks {
        commitMsg {
            conventionalCommits {
                defaultTypes()
                types("wip", "other", "deps")
            }
        }
        preCommit {
            from {
                ""//./gradlew format-fix
            }
            appendScript {
                ""// && git add .
            }
        }
        createHooks(overwriteExisting = true)
    }
}



rootProject.name = "revue"

include(
    "domain", 
    "common", 
    "monitoring", 
    "frontend", 
    "auth", 
    "alarm", 
    "notification", 
    "kafka", 
    "camera", 
    "sensor", 
    "log", 
    "recognition", 
    "media-server", 
    "user",
    "location"
)
