services:

  revue-auth:
    image: letsdothisshared/revue-auth
    container_name: ${AUTH_HOST}
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    restart: on-failure
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    depends_on:
      - revue-auth-db
    networks:
      - my-net
    labels:
      kompose.service.expose: "auth.localhost"
      traefik.enable: true
      traefik.http.routers.auth.rule: Host(`auth.localhost`)
      traefik.http.routers.auth.entrypoints: web # websecure

  revue-auth-db:
    image: mongo
    container_name: ${AUTH_DB_HOST}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${AUTH_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${AUTH_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${AUTH_DB_NAME}
    ports:
      - ${AUTH_DB_PORT}:27017
    volumes:
      - revue_auth_data:/data/db
      - ./auth/db/auth-init.js:/docker-entrypoint-initdb.d/auth-init.js
    networks:
      - my-net
    labels:
      kompose.service.type: clusterip
      kompose.controller.type: deployment

volumes:
  revue_auth_data:
    name: revue-auth-data
    driver: local

networks:
  my-net:
    name: revue-network
    external: true
