openapi: 3.0.0
info:
    title: Device Service API
    description: Device management and monitoring microservice API
    version: 1.0.0
tags:
    - name: Alarm
      description: Operations related to devices

paths:
    /rules/{id}/:
        get:
            summary: Get a rule by Id
            tags: [Alarm]
            responses:
                200:
                    description: The rule details
                403:
                    description: User is not authorized
        delete:
            summary: Delete a rule
            tags: [Alarm]
            responses:
                200:
                    description: The rule was correctly deleted
                403:
                    description: User is not authorized
                404:
                    description: The rule was not found
    /rules/{id}/contacts/:
        get:
    /rules/ranges/:
        get:
            summary: Get all ranges rules
            tags: [Alarm]
            responses:
                200:
                    description: The list of all the range rules
                403:
                    description: User not authorized
        post:
            summary: Create a new range rule
            tags: [Alarm]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/RangeRule"
            responses:
                201:
                    description: The rule was created successfully
                400:
                    description: The request was invalid
                403:
                    description: User not authorized
    /rules/ranges/{id}:
        get:
            summary: Get a range rule by Id
            tags: [Alarm]
            responses:
                200:
                    description: The range rule details
                403:
                    description: User is not authorized
        put:
            summary: Edit a range rule
            tags: [Alarm]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/RangeRule"
            responses:
                200:
                    description: The rule was correctly updated
                403:
                    description: User is not authorized
                404:
                    description: The rule was not found
    /rules/intrusions/:
        get:
            summary: Get all intrusion rules
            tags: [Alarm]
            responses:
                200:
                    description: The list of all the intrusion rules
                403:
                    description: User not authorized
        post:
            summary: Create a new intrusion rule
            tags: [Alarm]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/RangeRule"
            responses:
                201:
                    description: The rule was created successfully
                400:
                    description: The request was invalid
                403:
                    description: User not authorized
    /rules/intrusions/{id}:
        get:
            summary: Get an intrusion rule by Id
            tags: [Alarm]
            responses:
                200:
                    description: The intrusion rule details
                403:
                    description: User is not authorized
        put:
            summary: Edit an intrusion rule
            tags: [Alarm]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/IntrusionRule"
            responses:
                200:
                    description: The range rule was correctly updated
                403:
                    description: User is not authorized
