@startuml

package Device <<Rectangle>> {
    !includesub Device.puml!DeviceRoot
}

package Monitoring <<Rectangle>> {
    !includesub Monitoring.puml!MonitoringRoot
}

package Anomaly <<Rectangle>> {
    !includesub Alarm.puml!AnomalyRoot
}

package SecurityRule <<Rectangle>> {
    !includesub Alarm.puml!SecurityRuleRoot
}

package AlarmSystem <<Rectangle>> {
    !includesub Alarm.puml!AlarmServiceRoot
}

MonitoringRoom <<root>>
DeviceService <<root>>

MonitoringRoom -right- AlarmService
MonitoringRoom -- DeviceService


@enduml
