@startuml

!startsub Device

enum DeviceType {
  CAMERA
  SENSOR
}

interface DeviceId {
 + getType(): DeviceType
 + getCode(): String
}
DeviceId o-- DeviceType

interface Device {
 + getDeviceId(): DeviceId
 + getIpAddress(): String
 + isCapturing(): Boolean
 + startCapturing(): void
 + stopCapturing(): void
}
Device o-right- DeviceId

note left: Entity

interface DeviceFactory {
 + createSensor(): Device
 + createCamera(): Device
}
note left: Factory
DeviceFactory --> Device: creates

interface Camera {
 + getResolution(): Resolution
}
note left: Entity
Camera o-- Resolution
Device *-- Camera
Device *-- Sensor

interface Sensor {
 + getIntervalMillis(): Int
 + getMeasures(): Set<Measure>
 + addMeasure(): void
 + sendEnvironmentData(): void
}
note left: Entity
Sensor --> EnvironmentData : uses
Sensor o-- Measure


interface EnvironmentData {
 + getSourceDeviceId(): DeviceId
 + getValue(): Float
 + getMeasure(): Measure
 + getTimestamp(): Date
}

note right: Value Object

class Resolution {
 + height
 + width
}

enum Measure {
 HUMIDITY
 TEMPERATURE
 PRESSURE
 ...
}

!endsub Device

@enduml
