services:
  prometheus:
    image: prom/prometheus
    container_name: revue-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/etc/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: revue-grafana
    ports:
      - "8083:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password

    volumes:
      - ./prometheus/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./prometheus/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./prometheus/grafana/dashboards:/var/lib/grafana/dashboards


volumes:
  prometheus_data:
    driver: local
