# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
# If you want to customize Grafana instance

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server:80
      isDefault: true

persistence:
  type: pvc
  enabled: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes-views-global:
      gnetId: 15757
      revision: 37
      datasource: Prometheus

    kubernetes-views-nodes:
      gnetId: 15759
      revision: 29
      datasource: Prometheus

    kubernetes-views-pods:
      gnetId: 15760
      revision: 28
      datasource: Prometheus

    kubernetes-api-server:
      gnetId: 15761
      revision: 17
      datasource: Prometheus
