persistence:
  type: pvc
  enabled: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes-views-global:
      gnetId: 15757
      revision: 37

    kubernetes-views-nodes:
      gnetId: 15759
      revision: 29

    kubernetes-views-pods:
      gnetId: 15760
      revision: 28

    kubernetes-api-server:
      gnetId: 15761
      revision: 17
