
@startuml

package "Common Domain Entity" as Common {}
package "Auth" as Auth {}
package "User" as User {}
package "Location" as Location {}
package "DeviceMonitoring" as DeviceMonitoring {}
package "Alarm" as Alarm {}
package "Log" as Log {}
package "Notification" as Notification {}

note right of Common
    Shared Kernel
end note


/'Common -[bold]-> Auth
Common -[bold]-> User
Common -[bold]-> Location
Common -[bold]-> DeviceMonitoring
Common -[bold]-> Alarm
Common -[bold]-> Log
Common -[bold]-> Notification'/

Alarm -[bold]-> Notification : "P"


@enduml

