apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: monitoring-data
  name: monitoring-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
