apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-kafka
  name: revue-kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9094"
      port: 9094
      targetPort: 9094
  selector:
    io.kompose.service: revue-kafka
