apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f all-docker-compose.yml -o k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: revue-zookeeper
  name: revue-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: revue-zookeeper
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f all-docker-compose.yml -o k8s
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/revue-network: "true"
        io.kompose.service: revue-zookeeper
    spec:
      containers:
        - env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          image: bitnami/zookeeper:latest
          name: revue-zookeeper
          ports:
            - containerPort: 2181
              hostPort: 2181
              protocol: TCP
      restartPolicy: Always
