apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-log-db
  name: revue-log-db
spec:
  ports:
    - name: "27020"
      port: 27020
      targetPort: 27017
  selector:
    io.kompose.service: revue-log-db
  type: ClusterIP
