apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-location-db
  name: revue-location-db
spec:
  ports:
    - name: "27024"
      port: 27024
      targetPort: 27017
  selector:
    io.kompose.service: revue-location-db
