apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-log
  name: revue-log
spec:
  ports:
    - name: "4003"
      port: 4003
      targetPort: 4003
  selector:
    io.kompose.service: revue-log
  type: NodePort
