apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f all-docker-compose.yml -o k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.network/revue-network: "true"
    io.kompose.service: revue-auth
  name: revue-auth
spec:
  containers:
    - image: revue-auth
      name: revue-auth
      ports:
        - containerPort: 4000
          hostPort: 4000
          protocol: TCP
  restartPolicy: OnFailure
