apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-zookeeper
  name: revue-zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: revue-zookeeper
