apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-kafka-ui
  name: revue-kafka-ui
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8080
  selector:
    io.kompose.service: revue-kafka-ui
  type: NodePort
