apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-auth-db
  name: revue-auth-db
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: revue-auth-db
  type: ClusterIP
