apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.network/revue-network: "true"
    io.kompose.service: revue-camera-2
  name: revue-camera-2
spec:
  containers:
    - env:
        - name: CAMERA_CODE
          value: cam-02
        - name: CAMERA_PORT
          value: "5002"
      image: letsdothisshared/revue-camera
      imagePullPolicy: IfNotPresent
      name: revue-camera-2
      ports:
        - containerPort: 5002
          hostPort: 5002
          protocol: TCP
  restartPolicy: OnFailure
