apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.enable: "true"
    traefik.http.routers.alarm.entrypoints: websecure
    traefik.http.routers.alarm.rule: Host(`alarm.localhost`)
    traefik.http.routers.alarm.tls.certresolver: myresolver
  labels:
    io.kompose.service: revue-alarm
  name: revue-alarm
spec:
  ports:
    - name: "4002"
      port: 4002
      targetPort: 4002
  selector:
    io.kompose.service: revue-alarm
