apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.enable: "true"
    traefik.http.routers.log.entrypoints: websecure
    traefik.http.routers.log.rule: Host(`log.localhost`)
    traefik.http.routers.log.tls.certresolver: myresolver
  labels:
    io.kompose.service: revue-log
  name: revue-log
spec:
  ports:
    - name: "4003"
      port: 4003
      targetPort: 4003
  selector:
    io.kompose.service: revue-log
