apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-monitoring-db
  name: revue-monitoring-db
spec:
  ports:
    - name: "27018"
      port: 27018
      targetPort: 27017
  selector:
    io.kompose.service: revue-monitoring-db
  type: ClusterIP
