apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.network/revue-network: "true"
    io.kompose.service: revue-alarm
  name: revue-alarm
spec:
  containers:
    - image: letsdothisshared/revue-alarm
      name: revue-alarm
      ports:
        - containerPort: 4002
          hostPort: 4002
          protocol: TCP
  restartPolicy: OnFailure
