apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-recognition
  name: revue-recognition
spec:
  ports:
    - name: "4005"
      port: 4005
      targetPort: 4005
  selector:
    io.kompose.service: revue-recognition
  type: ClusterIP
