apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f all-docker-compose.yml -o k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: revue-monitoring
  name: revue-monitoring
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
  selector:
    io.kompose.service: revue-monitoring
