apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f all-docker-compose.yml -o k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.network/revue-network: "true"
    io.kompose.service: revue-alarm
  name: revue-alarm
spec:
  containers:
    - image: revue-alarm
      name: revue-alarm
      ports:
        - containerPort: 4002
          hostPort: 4002
          protocol: TCP
  restartPolicy: OnFailure
