apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.network/revue-network: "true"
    io.kompose.service: revue-sensor-1
  name: revue-sensor-1
spec:
  containers:
    - env:
        - name: SENSOR_CODE
          value: sen-01
        - name: SENSOR_PORT
          value: "6001"
      image: letsdothisshared/revue-sensor
      imagePullPolicy: IfNotPresent
      name: revue-sensor-1
      ports:
        - containerPort: 6001
          hostPort: 6001
          protocol: TCP
  restartPolicy: OnFailure
