apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-notification
  name: revue-notification
spec:
  ports:
    - name: "4004"
      port: 4004
      targetPort: 4004
  selector:
    io.kompose.service: revue-notification
  type: NodePort
