apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-monitoring
  name: revue-monitoring
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
  selector:
    io.kompose.service: revue-monitoring
  type: NodePort
