apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-alarm
  name: revue-alarm
spec:
  ports:
    - name: "4002"
      port: 4002
      targetPort: 4002
  selector:
    io.kompose.service: revue-alarm
  type: NodePort
