apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-device-db
  name: revue-device-db
spec:
  ports:
    - name: "27023"
      port: 27023
      targetPort: 27017
  selector:
    io.kompose.service: revue-device-db
