apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-notification-db
  name: revue-notification-db
spec:
  ports:
    - name: "27021"
      port: 27021
      targetPort: 27017
  selector:
    io.kompose.service: revue-notification-db
  type: ClusterIP
