apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: revue-notification-db-claim1
  name: revue-notification-db-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
