apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-sensor-2
  name: revue-sensor-2
spec:
  ports:
    - name: "6002"
      port: 6002
      targetPort: 6002
  selector:
    io.kompose.service: revue-sensor-2
  type: ClusterIP
