apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-camera-2
  name: revue-camera-2
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5002
  selector:
    io.kompose.service: revue-camera-2
  type: ClusterIP
