apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f all-docker-compose.yml -o k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.network/revue-network: "true"
    io.kompose.service: revue-camera-2
  name: revue-camera-2
spec:
  containers:
    - env:
        - name: CAMERA_CODE
          value: cam-02
        - name: CAMERA_PORT
          value: "5002"
      image: revue-camera
      name: revue-camera-2
      ports:
        - containerPort: 5002
          hostPort: 5002
          protocol: TCP
  restartPolicy: OnFailure
