apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-kafka-2
  name: revue-kafka-2
spec:
  ports:
    - name: "9093"
      port: 9093
      targetPort: 9093
    - name: "9095"
      port: 9095
      targetPort: 9095
  selector:
    io.kompose.service: revue-kafka-2
  type: NodePort
