apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: revue-auth-db
  name: revue-auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: revue-auth-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/revue-network: "true"
        io.kompose.service: revue-auth-db
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: auth
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo
          imagePullPolicy: IfNotPresent
          name: revue-auth-db
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: auth-data
      restartPolicy: Always
      volumes:
        - name: auth-data
          persistentVolumeClaim:
            claimName: auth-data
