apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: revue-user-db
  name: revue-user-db
spec:
  ports:
    - name: "27022"
      port: 27022
      targetPort: 27017
  selector:
    io.kompose.service: revue-user-db
