@startuml

package Device <<Rectangle>> {
    !includesub Device.puml!DeviceRoot
}

package Monitoring <<Rectangle>> {
    !includesub Monitoring.puml!MonitoringRoot
}

package Anomaly <<Rectangle>> {
    !includesub Alarm.puml!AnomalyRoot
}

package SecurityRule <<Rectangle>> {
    !includesub Alarm.puml!SecurityRuleRoot
}



DeviceService <<aggregate root>>


@enduml
