@startuml

!include Alarm.puml

package Device <<Rectangle>> {
    !include Device.puml
}

package Monitoring <<Rectangle>> {
    !include Monitoring.puml
}

MonitoringRoom <<aggregate root>>
DeviceService <<aggregate root>>

MonitoringRoom -down- AlarmService
MonitoringRoom -down- DeviceService


@enduml
