@startuml

interface Anomaly {
  + getAnomalyId(): Int
  + getDeviceId(): DeviceId
  + getTimestamp(): Date
}

interface Exceeding {
  + getValue(): Float,
  + getMeasure(): Measure
}

interface Intrusion {
  + getIntrusionObject(): ObjectClass
}

Exceeding *-- Anomaly
Intrusion *-- Anomaly

!startsub AnomalyRoot
interface AnomalyService {
  + addAnomaly(anomaly: Anomaly): void
  + removeAnomaly(anomalyId: String): void
  + notifyAlarmService(anomaly: Anomaly): void
}
!endsub AnomalyRoot

interface AnomalyFactory {
  + createIntrusion(): Anomaly
  + createExceeding(): Anomaly
}
AnomalyFactory --> Anomaly : creates
AnomalyFactory <-- AnomalyService : uses

interface AnomalyRepository {
  + getAnomalies(): Set<Anomaly>
  + insertAnomaly(anomaly: Anomaly): void
  + deleteAnomaly(anomalyId: Int): void
}
AnomalyRepository o-up- Anomaly
AnomalyService --> AnomalyRepository : uses

@enduml
