@startuml

interface DomainEventId {
  + getValue(): string
}

interface DomainEvent {
  + getId(): DomainEventId
  + getTimestamp(): Date
}

interface DeviceEvent {
  + getDeviceId(): DeviceId
}

interface Detection {
  + getObjectClass(): ObjectClass
}
interface Measurement {
  + getMeasureType(): MeasureType
  + getValue(): Float
}

interface Notification {
  + getMessage(): string
  + getEvent(): DomainEvent
}

interface Anomaly
interface Intrusion {
  + getDetection(): Detection
  + getIntrusionRule(): IntrusionRule
}

interface Outlier {
  + getMeasurement(): Measurement
  + getRangeRule(): RangeRule
}

DomainEvent *-left- DomainEventId

DomainEvent <|-- DeviceEvent
DomainEvent <|-- Notification
DeviceEvent <|-- Measurement
DeviceEvent <|-- Detection

DomainEvent <|-- Anomaly
Anomaly <|-- Intrusion
Anomaly <|-- Outlier

Notification o-- DomainEvent

Outlier o-- Measurement
Intrusion o-up- Detection

@enduml
