openapi: 3.0.0
info:
    title: User Authentication and Authorization Service API
    description: User authentication and user permissions microservice API
    version: 1.0.0
tags:
    -   name: UserAuth
        description: Operations related to user authentication and user permissions

paths:
    /login:
        post:
            summary: Log into the application
            tags: [ UserAuth ]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/Credentials"
            responses:
                200:
                    description: Login successful
                    content:
                        application/json:
                            schema:
                                $ref: "./schemas.yml#/components/schemas/Authorization"
                400:
                    description: The request was invalid
                403:
                    description: User not authorized
    /refresh:
        post:
            summary: Get a new token
            tags: [ UserAuth ]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/Token"
            responses:
                200:
                    description: Token updated
                    content:
                        application/json:
                            schema:
                                $ref: "./schemas.yml#/components/schemas/Token"
                400:
                    description: The request was invalid
                403:
                    description: User not authorized

    /permissions:
        get:
            summary: Get the list of locations to which the user has access
            tags: [ UserAuth ]
            responses:
                200:
                    description: The list of locations to which the user has access
                    content:
                        application/json:
                            schema:
                                $ref: "./schemas.yml#/components/schemas/Permissions"
                403:
                    description: User not authorized

    /permissions/{userId}:
        get:
            summary: Get the list of locations to which a user has access
            tags: [ UserAuth ]
            responses:
                200:
                    description: The list of locations to which the user has access
                    content:
                        application/json:
                            schema:
                                $ref: "./schemas.yml#/components/schemas/Permissions"
                403:
                    description: User not authorized
                404:
                    description: User not found
        post:
            summary: Set user permissions
            tags: [ UserAuth ]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/Permissions"
            responses:
                200:
                    description: User's permissions updated
                400:
                    description: Invalid request
                403:
                    description: User not authorized
                404:
                    description: User not found
        put:
            summary: Add user permissions
            tags: [ UserAuth ]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/Permissions"
            responses:
                200:
                    description: User's permissions updated
                400:
                    description: Invalid request
                403:
                    description: User not authorized
                404:
                    description: User not found
        delete:
            summary: Remove user permissions
            tags: [ UserAuth ]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/Permissions"
            responses:
                200:
                    description: User's permissions updated
                400:
                    description: Invalid request
                403:
                    description: User not authorized
                404:
                    description: User not found
    /users:
        get:
            summary: Get all users
            tags: [ UserAuth ]
            responses:
                200:
                    description: The list of all users
                403:
                    description: User not authorized
        post:
            summary: Create a new user
            tags: [ UserAuth ]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/User"
            responses:
                201:
                    description: The user was created successfully
                400:
                    description: The request was invalid
                403:
                    description: User not authorized
    /users/{userId}:
        get:
            summary: Get a user by ID
            tags: [ UserAuth ]
            responses:
                200:
                    description: The user was found
                    content:
                        application/json:
                            schema:
                                $ref: "./schemas.yml#/components/schemas/User"
                404:
                    description: User not found
                403:
                    description: User not authorized
        put:
            summary: Update a user by ID
            tags: [ UserAuth ]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/User"
            responses:
                200:
                    description: The user was updated
                400:
                    description: The request was invalid
                403:
                    description: User not authorized
                404:
                    description: User not found
        delete:
            summary: Delete a user by ID
            tags: [ UserAuth ]
            responses:
                200:
                    description: The user was deleted
                400:
                    description: The request was invalid
                403:
                    description: User not authorized
                404:
                    description: User not found
