@startuml

left to right direction

rectangle {
    portin entrypoint

cloud Kafka

rectangle Microservices {
    component Monitoring
    component Auth
    component Alarm
    component Log

    component Notification
    component Recognition

}
component MediaServer
component Frontend
rectangle "Devices" {
    component Sensor <<web server>>
    component Camera <<web server>>
}
interface API
Microservices -up- API
Frontend -- API : Requests


Kafka <-- Recognition
Kafka --> Monitoring
Kafka --> Log
Kafka --> Alarm
Kafka <-up- Sensor

MediaServer <-- Camera : RTSP
MediaServer --> Frontend: WebRTC
MediaServer --> Recognition: RTSP
}

actor Client
Client --> entrypoint
entrypoint --> Frontend

legend
    Kafka --> Service : Consume
    Kafka <-- Service : Produce
end legend


@enduml
