openapi: 3.0.0
info:
    title: Device Service API
    description: Device management and monitoring microservice API
    version: 1.0.0
tags:
    -   name: Devices
        description: Operations related to devices

paths:
    /devices:
        get:
            summary: Get all devices
            tags: [ Devices ]
            parameters:
                -   in: query
                    name: capabilities
                    required: false
                    schema:
                        type: array
                        items:
                            type: string
                    description: The capabilities that the devices must have
            responses:
                200:
                    description: The list of all devices to which the user has access
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "./schemas.yml#/components/schemas/Device"
                403:
                    description: User not authorized
        post:
            summary: Join a new device to the system
            tags: [ Devices ]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/Device"
            responses:
                201:
                    description: The camera was created successfully
                400:
                    description: The request was invalid
                403:
                    description: User not authorized
    /devices/actives:
        get:
            summary: Get all active devices
            tags: [ Devices ]
            responses:
                200:
                    description: The list of all active devices
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "./schemas.yml#/components/schemas/Device"
                403:
                    description: User not authorized
    /devices/{id}:
        get:
            summary: Get a device by id
            tags: [ Devices ]
            parameters:
                -   in: path
                    name: id
                    required: true
                    schema:
                        $ref: "./schemas.yml#/components/schemas/DeviceId"
            responses:
                200:
                    description: The device with the specified ID
                    content:
                        application/json:
                            schema:
                                $ref: "./schemas.yml#/components/schemas/Device"
                400:
                    description: The request was invalid
                403:
                    description: User not authorized

        put:
            summary: Update a device
            tags: [ Devices ]
            parameters:
                -   in: path
                    name: id
                    required: true
                    schema:
                        $ref: "./schemas.yml#/components/schemas/DeviceId"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "./schemas.yml#/components/schemas/Device"
            responses:
                200:
                    description: The device was updated successfully
                400:
                    description: The request was invalid
                403:
                    description: User not authorized
        delete:
            summary: Delete a device
            tags: [ Devices ]
            parameters:
                -   in: path
                    name: id
                    required: true
                    schema:
                        $ref: "./schemas.yml#/components/schemas/Device"
            responses:
                204:
                    description: The resource was deleted successfully
                400:
                    description: The request was invalid
                403:
                    description: User not authorized
