services:

  revue-device:
    image: letsdothisshared/revue-device
    container_name: ${DEVICE_HOST}
    build:
      context: .
      dockerfile: ./device/Dockerfile
    restart: on-failure
    ports:
      - ${DEVICE_PORT}:${DEVICE_PORT}
    depends_on:
      - revue-device-db
      - ${KAFKA_HOST}
    networks:
      - my-net

    labels:
      - traefik.enable=true
      - traefik.http.routers.device.rule=Host(`localhost:${DEVICE_PORT}`)

  revue-device-db:
    image: mongo
    container_name: ${DEVICE_DB_HOST}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEVICE_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DEVICE_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DEVICE_DB_NAME}
    ports:
      - ${DEVICE_DB_PORT}:27017
    volumes:
      - device_data:/data/db
      - ./device/db/device-init.js:/docker-entrypoint-initdb.d/device-init.js
    networks:
      - my-net

volumes:
  device_data:
    driver: local

networks:
  my-net:
    name: revue-network
    external: true
