@startuml

start
:Node Initialization;

repeat :Check Kafka Connection;
repeat while (connected?) is (no) not (yes)

repeat :Get Streaming Video;
repeat while (streaming available?) is (no) not (yes)

repeat :Send Stream to Kafka;
repeat while (terminate?) is (no) not (yes)

stop

@enduml