@startuml
'https://plantuml.com/sequence-diagram
participant Camera
participant "Media Server"
participant Frontend
actor ":User" as User
participant Notification
participant Recognition
participant Alarm

Camera -> "Media Server": Produce stream \nusing RTSP
"Media Server" -> Frontend: Get stream \nusing WebRTC
"Media Server" -> Recognition: Get stream\nusing RTSP
Recognition -> Recognition: Start recognizing
Recognition -> Alarm: Send recognized objects
Alarm -> Alarm: Check \nintrusions
opt Data violating intrusion rule
Alarm -> Notification: Create notification
Notification -> Frontend: Update
Notification -> User: SMS
Notification -> User: Email
end
@enduml
