@startuml
'https://plantuml.com/component-diagram

component Kafka
component Frontend
component Auth
component Monitoring
component Alarm
component Notification
component Recognition
component Log
component "Media Server" as MediaServer
component Sensor
component Camera

Sensor -up-> Kafka
Monitoring -up-> Kafka
Log -up-> Kafka
Alarm -up-> Kafka
Frontend -up-> Auth
Frontend -up-> Notification
Frontend -up-> Monitoring
Frontend -up-> Alarm
Frontend -up-> MediaServer
Sensor -up-> Monitoring
Camera -up-> Monitoring
Camera -up-> MediaServer
Alarm -up-> Notification
Recognition -up-> Alarm
Recognition -up-> MediaServer
Frontend -up-> Log


@enduml
