name: Revue Build

on:
  push:
    branches: [ '**', '!main' ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    # run on ubuntu, windows and macOS
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run build
        run: ./gradlew build --info
      - name: Run tests
        run: ./gradlew auth:test  alarm:test --info || ./gradlew monitoring:test recognition:test --info

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Check format
        run: ./gradlew format --info
      - name: Check lint
        run: ./gradlew lint --info
