name: Revue CI

on:
  push:
    branches: [ '**', '!main' ]
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build
        run: ./gradlew build --info
      - name: Test
        run: ./gradlew auth:test user:test alarm:test --info || ./gradlew monitoring:test recognition:test --info

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Check format
        run: ./gradlew format --info
      - name: Check lint
        run: ./gradlew lint --info

  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Pre-compute the next version
        id: compute-next-version
        uses: nicolasfara/precompute-semantic-release-version-action@1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use the next version
        run: |
          echo "Will release: ${{ steps.compute-next-version.outputs.will-release }}"
          echo "The next version is ${{ steps.compute-next-version.outputs.next-version }}"
